name: simple_flutter_app
description: A minimal Flutter app created by Copilot.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0
  gradient_borders: ^0.2.0
  dropdown_button2: ^1.9.0
  shimmer: ^2.0.0
  intl: ^0.19.0
  smooth_page_indicator: ^1.0.0


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/student5.png
    - assets/student pc.png
    - assets/job2.png
    - assets/soc11.png
    - assets/soc2.png
    - assets/man.png
    - assets/et.png
    - assets/etudiant3.png
    - assets/clÃ©.png
    - assets/firenze.Jpg
    - assets/milano.Jpg
    - assets/roma.Jpg
    - assets/Urbino.Jpg
    - assets/studentt.png
    - assets/emp.png

    - assets/img 4.png
    - assets/img 5.png

  


